apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: loxus46mi-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:52b90cec80a7bf68e77580102adeed5d9a6ff75a@sha256:95733629e1a3d15c292e7550ae6f4f00313fd68ef9e466ccb434dbbc740bb3c5
          name: container-image
